name: CoreFunctionality
version: '${project.version}'
main: com.smellyalater.corefunctionality.CoreFunctionality
api-version: 1.18
authors: [ Smellyalater ]
description: Core functionality for the server 8)
dependencies:
  - NBTAPI

commands:
  levelinfo:
    permission: corefunctionality.levelinfo
    description: levelinfo
  skills:
    permission: corefunctionality.skills
    description: skills
  giveSkillPoints:
    permission: corefunctionality.giveSkillPoints
    description: giveSkillPoints