name: CoreFunctionality
version: '${project.version}'
main: com.smellyalater.corefunctionality.CoreFunctionality
api-version: 1.18
authors: [ Smellyalater ]
description: Core functionality for the server 8)
dependencies:
  - NBTAPI
  - WorldGuard

commands:
  levelinfo:
    permission: corefunctionality.levelinfo
    description: levelinfo
  giveSkillPoints:
    permission: corefunctionality.giveSkillPoints
    description: giveSkillPoints
  resetPlayer:
    permission: corefunctionality.resetPlayer
    description: resetPlayer